# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLab3():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_lab3(self):
    self.driver.get("https://tutorialsninja.com/demo/")
    self.driver.set_window_size(699, 562)
    self.driver.find_element(By.CSS_SELECTOR, ".product-layout:nth-child(1) button:nth-child(1)").click()
    self.driver.execute_script("window.scrollTo(0,819)")
    elements = self.driver.find_elements(By.CSS_SELECTOR, "h1")
    assert len(elements) > 0
  
